# -*- coding: utf-8 -*-
"""DGSI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a_ku48XFHubMjnO4UACXx_2vQ_MYFAlF
"""

# Install whisper and check its presence
!pip install -q insanely-fast-whisper
!pip install transformers torch faiss-cpu
!pip install -q yt-dlp

import yt_dlp

# Local variables

whisper_path = "/usr/local/bin/insanely-fast-whisper"
example_URL = "https://www.signalogic.com/melp/EngSamples/Orig/male.wav"

download_path = "/tmp/example_audio.wav"

# Get the audio
!wget {example_URL} -O {download_path}



def transcribe_audio(audio_path, output_path):
  !{whisper_path} --file-name {audio_path} --transcript-pat {output_path}

# Transcribe
output_example_path = "/content/example_output.json"
transcribe_audio(download_path, output_example_path)

# Print the Json
import json

with open(output_example_path, 'r') as file:
    transcription = json.load(file)

# Display
# print(json.dumps(transcription, indent=2))

def print_json(json_path):
  with open(json_path, 'r') as f:
      data = json.load(f)

  # Text
  full_text = data['text']
  print("Full Text:\n", full_text)

  # Timestamped chunks
  for chunk in data['chunks']:
      start, end = chunk['timestamp']
      text = chunk['text']
      print(f"From {start}s to {end}s: {text}")

print_json(output_example_path)

def download_youtube_audio(youtube_url, output_path):
  ydl_opts = {
      'format': 'bestaudio/best',
      'outtmpl': output_path,
      'noplaylist': True,
      'postprocessors': [{
          'key': 'FFmpegExtractAudio',
          'preferredcodec': 'mp3',
          'preferredquality': '192',
      }],
  }

  with yt_dlp.YoutubeDL(ydl_opts) as ydl:
    ydl.download([youtube_url])

# Example usage
youtube_url = "https://www.youtube.com/shorts/pn_CWfFFkB8"
yt_example_url = "/content/downloaded_audio"

download_youtube_audio(youtube_url, yt_example_url)

print(f"Audio downloaded to: {yt_example_url}")

output_yt_example = "/content/yt_example_output.json"

transcribe_audio(yt_example_url + ".mp3", output_yt_example)

print_json(output_yt_example)